[program:synergia-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/synergia/artisan queue:work database --sleep=3 --tries=3 --timeout=120 --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/synergia/storage/logs/worker.log
stopwaitsecs=3600
