<section id="participants" class="band white" lang="es">
    <div class="wrap section-head">
        <p class="eyebrow">Información para pacientes — borrador para revisión</p>
        <h2>Para pacientes, familias y miembros de la comunidad.</h2>
        <p>La participación en investigación clínica se explica con claridad, se revisa cuidadosamente y se gestiona mediante procesos de estudio aprobados.</p>
        <p><a class="button dark" href="{{ route('medisana.research-center', ['page' => 'patients']) }}">Ver en inglés</a></p>
    </div>
    <figure class="wrap section-visual">
        <img src="{{ asset('images/medisana/Medisana_Patient_Families_Community.png') }}" alt="Pacientes, familias y miembros de la comunidad participando en investigación clínica con Medisana Research Center" width="1536" height="1024" loading="eager" decoding="async">
    </figure>
    <div class="wrap grid four">
        <article class="card accent-teal"><h3>Conozca la investigación</h3><p>Las oportunidades de estudio se comparten únicamente cuando las aprobaciones, los materiales del estudio y los procesos del centro están listos.</p></article>
        <article class="card accent-blue"><h3>Entienda su decisión</h3><p>La participación es voluntaria. Antes del consentimiento, cada estudio explica su propósito, riesgos, beneficios, visitas, privacidad y alternativas.</p></article>
        <article class="card accent-gold"><h3>Proteja su privacidad</h3><p>La información de salud protegida se maneja mediante procesos seguros del estudio. El correo electrónico general se reserva para preguntas básicas.</p></article>
        <article class="card accent-teal"><h3>Apoyo durante las visitas</h3><p>Cuando sea apropiado y el estudio lo permita, Medisana puede ayudar a coordinar transporte, recordatorios y servicios de apoyo en el hogar.</p></article>
    </div>
    <div class="wrap current-studies" id="currently-enrolling" aria-label="Estudios actualmente en inscripción">
        <div class="current-studies-copy"><p class="eyebrow">Estudios actualmente en inscripción</p><h3>Las oportunidades aprobadas aparecerán aquí cuando estén listas para divulgación pública.</h3><p>Medisana publicará resúmenes de estudios aprobados por el patrocinador o el IRB solamente cuando estén listos los materiales, la ruta de privacidad y el lenguaje para participantes.</p></div>
        <div class="study-listings"><article class="study-listing"><span>Tablero de inscripción</span><strong>No hay estudios públicos listados en este momento.</strong><p>Cuando se abra un estudio, esta área podrá mostrar el área de salud, el rango básico de edad, el lugar de las visitas, disponibilidad de transporte y cómo solicitar una preselección segura.</p><a class="button dark" href="#participant-interest">Solicitar actualizaciones de estudios</a></article><article class="study-listing muted"><span>Enfoque de información pública</span><strong>Resúmenes en lenguaje claro antes de la preselección segura.</strong><p>Los resúmenes públicos mantienen información general; los detalles protegidos se reservan para el portal seguro de investigación.</p></article></div>
    </div>
    <div class="wrap patient-experience" aria-label="Qué ocurre durante un estudio aprobado">
        <div class="research-video"><div class="video-frame"><iframe title="NIMH: ¿Qué es la investigación clínica?" src="https://www.youtube-nocookie.com/embed/lJOQB_G15Jc" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="video-source"><span>Video educativo para pacientes</span><strong>NIMH: ¿Qué es la investigación clínica?</strong><p>La investigación clínica ayuda a mejorar la atención al responder preguntas cuidadosamente, con equipos capacitados, planes aprobados y controles de seguridad para participantes.</p><a href="https://www.youtube.com/watch?v=lJOQB_G15Jc" target="_blank" rel="noopener">Abrir el video directamente</a><br><a href="https://www.nimh.nih.gov/health/trials" target="_blank" rel="noopener">Ver recursos del NIMH para participantes</a></div></div>
        <div class="study-journey"><p class="eyebrow">Durante un estudio aprobado</p><h3>Qué pueden esperar los participantes cuando un estudio esté abierto.</h3><ol>
            <li><div><strong>Preselección y elegibilidad</strong><p>El equipo del estudio revisa criterios básicos y responde preguntas antes de que se tome cualquier decisión sobre investigación.</p></div></li>
            <li><div><strong>Consentimiento informado</strong><p>La visita explica el propósito, riesgos, beneficios, privacidad, tiempo requerido, alternativas y el carácter voluntario de la participación.</p></div></li>
            <li><div><strong>Visitas y evaluaciones del estudio</strong><p>Las visitas aprobadas por el protocolo pueden incluir exámenes, cuestionarios, laboratorios, diagnósticos, dispensación de medicamentos o seguimientos.</p></div></li>
            <li><div><strong>Apoyo durante las visitas cuando esté disponible</strong><p>La coordinación de transporte, los recordatorios y los servicios de apoyo en el hogar pueden reducir la carga de participación cuando sea apropiado y el estudio lo permita.</p></div></li>
            <li><div><strong>Monitoreo de seguridad</strong><p>El investigador principal y el equipo del estudio supervisan la seguridad, documentan inquietudes y coordinan con el patrocinador, CRO e IRB cuando sea necesario.</p></div></li>
            <li><div><strong>Finalización o retiro</strong><p>Los participantes pueden completar las visitas programadas o decidir retirarse del estudio, con orientación para hacerlo de forma segura.</p></div></li>
        </ol></div>
    </div>
    <div class="wrap pathway-board" id="participant-interest" aria-label="Proceso de solicitud de información y preselección de participantes">
        <div class="pathway-panel"><p class="eyebrow">Proceso para participantes</p><h3>Solicite información ahora. Complete la preselección segura solo cuando haya un estudio listo.</h3><p>Los pacientes y familiares pueden solicitar ser contactados sobre futuras oportunidades aprobadas. La preselección médica detallada se realiza mediante el portal seguro de investigación después de que estén establecidos la privacidad, el consentimiento, el control de acceso y los materiales aprobados por el IRB o patrocinador.</p><div class="intake-blueprint" aria-label="Categorías del cuestionario de preselección segura"><div class="intake-step"><strong>Perfil demográfico</strong><span>Rango de edad, sexo asignado al nacer, raza, origen étnico, idioma preferido, ubicación y preferencias de contacto cuando se necesiten para un estudio específico.</span></div><div class="intake-step"><strong>Condiciones médicas actuales y anteriores</strong><span>Historial de la condición específica del estudio, momento del diagnóstico, procedimientos relevantes y criterios de inclusión o exclusión.</span></div><div class="intake-step"><strong>Lista de medicamentos y tratamientos</strong><span>Medicamentos actuales, cambios recientes, alergias, terapias previas y requisitos relacionados con farmacia.</span></div><div class="intake-step"><strong>Revisión de elegibilidad y seguridad</strong><span>El personal de investigación revisa las respuestas conforme al protocolo aprobado antes de programar la evaluación, el consentimiento o las visitas.</span></div></div><div class="privacy-note">Los cuestionarios médicos detallados se reservan para el portal seguro de investigación cuando estén activos los controles de HIPAA, el acceso basado en roles, el lenguaje de consentimiento y las aprobaciones específicas del estudio.</div></div>
        <form class="public-form" data-mailto-form data-recipient="info@medisana-health.com" data-subject="Solicitud de información para participantes de estudio"><h3>Solicite información sobre estudios</h3><p>Para interés general, comparta sus preferencias de contacto y una pregunta general. Los detalles de salud protegidos se reservan para procesos seguros del portal.</p><div class="form-grid two"><div class="field"><label for="participant_name">Nombre</label><input id="participant_name" name="Nombre" type="text" autocomplete="name"></div><div class="field"><label for="participant_email">Correo electrónico</label><input id="participant_email" name="Correo electrónico" type="email" autocomplete="email"></div><div class="field"><label for="participant_phone">Teléfono</label><input id="participant_phone" name="Teléfono" type="tel" autocomplete="tel"></div><div class="field"><label for="participant_contact">Contacto preferido</label><select id="participant_contact" name="Contacto preferido"><option value="">Seleccione uno</option><option>Correo electrónico</option><option>Teléfono</option><option>Mensaje de texto</option></select></div><div class="field"><label for="participant_location">Ubicación más cercana</label><select id="participant_location" name="Ubicación más cercana"><option value="">Seleccione uno</option><option>Miami Springs</option><option>Flagler</option><option>Homestead</option><option>No estoy seguro/a</option></select></div><div class="field"><label for="participant_interest">Interés de investigación</label><select id="participant_interest" name="Interés de investigación"><option value="">Seleccione uno</option><option>Actualizaciones generales de estudios</option><option>Estudios de SNC o salud conductual</option><option>Estudios de bienestar o atención primaria</option><option>Consulta de cuidador o familiar</option><option>Aún no estoy seguro/a</option></select></div></div><div class="form-grid"><div class="field"><label for="participant_question">Pregunta general</label><textarea id="participant_question" name="Pregunta general" placeholder="Comparta una pregunta general sin detalles médicos."></textarea></div><label class="check-field"><input type="checkbox" name="Confirmación de privacidad" value="Confirmado"><span>Entiendo que este formulario es solo para información general; la información privada de salud se reserva para procesos seguros del portal.</span></label></div><div class="form-actions"><button class="button dark" type="submit">Enviar correo al equipo de investigación</button><a class="button" href="mailto:info@medisana-health.com?subject=Solicitud%20de%20información%20para%20participantes%20de%20estudio">Abrir correo electrónico</a></div><span class="form-note">Esto no inscribe a nadie en un estudio. Un integrante del equipo de investigación debe confirmar si existe alguna oportunidad aprobada disponible.</span></form>
    </div>
</section>
